version: '3.1'
services:
  user:
    container_name: user
    build:
      context: ./user-service/
      args:
        USER_DB_URL: ${USER_DB_URL}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - userdb
  post:
    container_name: post
    build:
      context: ./post-service/
      args:
        POST_DB_URL: ${POST_DB_URL}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - postdb
  userdb:
    image: postgres:14-alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=userdb
    volumes:
      - user-data:/var/lib/postgresql/data/
  postdb:
    image: postgres:14-alpine3.16
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=postdb
    volumes:
      - post-data:/var/lib/postgresql/data/
volumes:
  user-data:
  post-data: